packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@swc/core'
  - es5-ext
  - esbuild
  - unrs-resolver
  - workerd

patchedDependencies:
  '@cloudflare/vitest-pool-workers': patches/@cloudflare__vitest-pool-workers.patch
